# Numpy exercices pratiques
Ce notebook à pour objectif de vous faire pratiquer numpy dans toute sa généralité. 
Vous avez donc une liste de questions à faire ! Il ne faut pas hésiter à faire des recherches sur google ainsi que voir la [documentation officielle](https://docs.scipy.org/doc/numpy-1.13.0/reference/). 

#### Q1 : Importer le package numpy 

In [3]:
import numpy as np

#### Q2 : Afficher la version de numpy et la configuration 

In [4]:
import numpy as np
print(np.__version__)
print(np.show_config())

1.19.5
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
None


#### Q3 : Créer un vecteur nul de taille 10

In [6]:
c = np.zeros(10)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Q4 : Créer un vecteur null de taille 10 et affecter la valeur 1 à la 4ème place (index 4) du vecteur

In [7]:
c = np.zeros(10)
c[4] = 1
c

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### Q5 : Créer un vecteur Z de 40 valeurs allant de 10 à 50 

In [8]:
z = np.arange( 10, 51 )
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


#### Q6 : Inverser Z (le premier élément devient donc le dernier)

In [9]:
print(np.flip(z))

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### Q7 : Créer une matrice 3x3 avec des valeurs comprise entre 0 et 8 

In [10]:
x =  np.arange(0, 9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Q8 : Créer une matrice identié 3x3 

In [11]:
x = np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Q9 : Créer une matrice 3x3x3 avec des valeurs random 

In [12]:
x = np.random.random((3,3,3))
print(x)

[[[0.71324229 0.79948348 0.24778544]
  [0.9897166  0.33473455 0.40858532]
  [0.98013525 0.87782535 0.47872493]]

 [[0.73105768 0.14537014 0.62051729]
  [0.37051386 0.66991333 0.72163854]
  [0.95509779 0.56466724 0.55629116]]

 [[0.48490491 0.86804099 0.67408208]
  [0.30406191 0.65312121 0.9619166 ]
  [0.1574844  0.84786819 0.66390736]]]


#### Q10 : Créer une matrice 10x10 avec des valeurs random et afficher le minimum et maximum de cette matrice

In [13]:
x = np.random.random((10,10))
print(x)
print(x.min())
print(x.max())

[[0.49138511 0.79794914 0.30212842 0.43245595 0.97438376 0.55232152
  0.26509487 0.87034591 0.45456427 0.45753601]
 [0.72872879 0.68230219 0.11438758 0.46375791 0.25941357 0.34133908
  0.00348812 0.33040643 0.95860329 0.56801503]
 [0.549989   0.56639167 0.89304966 0.16175376 0.14036368 0.30945616
  0.45498351 0.96836212 0.32228794 0.56566455]
 [0.53553687 0.45905444 0.30293237 0.64117099 0.13209622 0.78514922
  0.91983921 0.89573851 0.26617691 0.46642977]
 [0.74531346 0.66292284 0.44495998 0.53690338 0.59375769 0.66501114
  0.79384945 0.82379837 0.90887776 0.76080501]
 [0.76015406 0.34894649 0.66161979 0.16942385 0.5929921  0.67194711
  0.67900898 0.17936362 0.33817823 0.3853902 ]
 [0.71989336 0.54785566 0.95894948 0.00621034 0.24100703 0.04263376
  0.35201605 0.65995941 0.75000757 0.6905684 ]
 [0.91535169 0.85252421 0.25619266 0.11688214 0.31066221 0.59336457
  0.84311819 0.98972514 0.5098679  0.42782565]
 [0.87947371 0.84318126 0.86967461 0.30679513 0.88299062 0.70532967
  0.62803826

#### Q11 : Créer une matrice 5x5 avec les valeurs 1,2,3,4 en dessous de la diagonale 

In [14]:
c = np.zeros((5,5))
a = np.array([1,2,3,4])
c = np.diag(a,-1)
print(c)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### Q12 : Créer une liste random de taille 5 et donner la somme de ses éléments  

In [26]:
total = np.random.randint(0,6, 5)
print(total)
somme = total.sum()
somme



[0 1 4 1 0]


6

#### Q13 : Créer une liste random de taille 5 et donner la moyenne de ses éléments

In [27]:
total = np.random.randint(0,6, 5)
print(total)
moyenne = total.mean()
moyenne

[4 0 5 0 5]


2.8

#### Q14 : En utilisant une fonction, donner la taille de la liste suivante :
```python 
l = [x for x in range(11)]
```

In [ ]:
l = [x for x in range(11)]
len(l)

#### Q15 : Créer un tableau de taille 10 avec des valeurs comprises entre 0 et 1 EXCLUS 

In [29]:
x = np.random.rand(10)
x

array([0.15231683, 0.52208824, 0.5128159 , 0.94950827, 0.27862355,
       0.17398514, 0.89786164, 0.39480255, 0.85880756, 0.62242578])

#### Q16 : Soit deux tableau A et B de dimension 1 et de taille 5, créer A et B et afficher True si A et B sont égaux False sinon

In [31]:
a = np.random.randint(0,6,5) 
b = np.random.randint(0,6,5)
print(a)
print(b)
comparison = a == b
equal_arrays = comparison.all()
print(equal_arrays)

[4 0 5 5 3]
[1 3 3 3 1]
False


#### Q17 : Convertir un tableau de float32 de dimension 1 et de taille 10 en un tableau de meme taille et dimension mais de type int32

In [36]:
x = np.random.uniform(0,5,10)
print(x)
y = x.astype(int)
print(y)

[1.72881163 1.95360564 3.93264203 3.11410661 1.06030284 2.17580908
 2.11212449 4.67404875 4.49768483 1.76164302]
[1 1 3 3 1 2 2 4 4 1]


#### Q18 : Normaliser une matrice random 5x5 
La normalisation d'un nombre X consiste à lui retirer sa moyenne et a diviser le tout par son écart type 

#### Q19 : Créer une matrice random `M` 2x2 et donner sa transposer 
L'opération de transposition dans une matrice consiste à échanger les lignes et le colonnes. 

#### Q20 : Écrire un petit script qui remplace un élément au hasard dans une matrice de dimension NxN

#### Q21 : Considérons une matrice de dimension (5,5,3), écrire un script qui multiplie cette matrice par une matrice de dimension (5,5)